Eco store/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

Eco store/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add_product', views.add_product, name='add_product'),
    path('search', views.search, name='search'),
    path('register_business', views.register_business, name='register_business'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('about', views.about, name='aboutpage')
]

Eco store/ecommerce_website_django/urls.py
from django.contrib import admin
from django.urls import path, include

#To show media file
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('accounts/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('about/', include('App_Shop.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco store/App_Shop/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('-created',)

class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.IntegerField()
    old_price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created',)

class Business(models.Model):
    class Meta:
        verbose_name_plural='Businesses'

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,default='')
    owner=models.CharField(max_length=120,default='')
    business_type = models.CharField(max_length=100,default='')
    registration_number = models.CharField(max_length=50, blank=True)
    tax_id = models.CharField(max_length=50, blank=True)
    street_address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100, blank=True)
    division = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

Eco store/App_Shop/forms.py
from django import forms
from .models import Product, Category,Business

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'preview_text', 'detail_text', 'category', 'price', 'old_price', 'mainimage']
    name=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter name of product',
        'class':'box'
    }))
    preview_text=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Preview text',
        'class':'box'
    }))
    detail_text=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Product Description',
        'class':'box'
    }))
    price=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Product New Price',
        'class':'box'
    }))
    old_price=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Product previous Price',
        'class':'box'
    }))
   
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        # Restrict category choices if needed (optional)
        self.fields['category'].queryset = Category.objects.all()  # Get all categories

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = ['name','owner', 'business_type', 'registration_number', 'tax_id', 'street_address', 'city', 'division', 'country']
    name=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter Business name',
        'class':'box'
    }))
    owner=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your name',
        'class':'box'
    }))
    business_type=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter Business type',
        'class':'box'
    }))
    registration_number=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter reg no',
        'class':'box'
    }))
    tax_id=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your tax ID',
        'class':'box'
    }))
    street_address=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter street number',
        'class':'box'
    }))
    city=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter current city',
        'class':'box'
    }))
    division=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter division',
        'class':'box'
    }))
    country=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter Country',
        'class':'box'
    }))
    

Eco store/App_Shop/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ProductForm,BusinessForm

# Import Views
from django.views.generic import ListView, DetailView

# Import Models
from App_Shop.models import Product,Category

# Mixins
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class Home(ListView):
    model = Product
    template_name = 'App_Shop/home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'


def add_product(request):
   
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)  # Include uploaded files
        if form.is_valid():
            new_product = form.save()  # Use form.save() for validated data
            messages.success(request, 'Product was added succesfully ')

            # Success message or redirect to product detail page
            return redirect('/') # Redirect with ID

        else:
            # Handle form errors (optional: display in the template)
            return render(request, 'App_Shop/add_product.html', {'form': form, 'categories': Category.objects.all()})
    else:
        form = ProductForm()  # Create an empty form for initial display
    return render(request, 'App_Shop/add_product.html', {'form': form, 'categories': Category.objects.all()})

def register_business(request):
    if request.method=='POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            new_business=form.save()
            messages.success(request, 'Business was registered succesfully ')
            return redirect('/')
        
        
    else:    
        form = BusinessForm()
        return render(request,'App_Shop/register_business.html',{'form':form})
    

def search(request):
    if request.method=='POST':
        searched=request.POST['search']
        searched=Product.objects.filter(name__icontains=searched)
        if not searched:
            messages.success(request,'That product does not exist, please try again')
            return render(request,'App_Shop/search.html',{})
        else:
            return render(request,'App_Shop/search.html',{'searched':searched})
    else:    
        return render(request,'App_Shop/search.html')
    
def about(request):
    return render(request, 'about.html')

Eco store/templates/App_Shop/add_product.html
{% extends "base.html" %} {% block body_block %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Product</title>
    <style>
      body{
        font-family: sans-serif;
        font-size: 18px;
        text-align: center;
        background-color: whitesmoke;
      }
      .box{
        background: none;
        display: flex;
        width: 500px;
        display: block;
        padding: 10px;
        border-left: none;
        border-top: none;
        border-right: none;
        border-bottom: solid;
        transition: 1s ease;
        

      }
      .form{
        text-align: justify;
        background: hsl(209, 34%, 87%);
        width: 600px;
        height: 750px;
        margin:  auto;
        /* padding:12px 20px; */
        border-radius: 20px;
        border: 1px solid white;
        align-items: center;
        padding: 50px;
        box-shadow: 15px 20px 20px rgb(139, 137, 137);
        
      }
      .btn{
        width: 300px;
        padding: 10px 20px;
        display: block;
        border: 0;
        outline: none;
        margin: auto;
        color: whitesmoke;
        background: #ffad06;
        margin-top: 10px;
        border-radius: 15px;
        transition: 0.3s ease;
        
      }
      .btn:hover{
        background-color: maroon;
      }
    </style>
  </head>
  <body>
    <h1>Add Product</h1>
   
    <br><br>
    <form action="" method="POST" enctype="multipart/form-data" class="form">

      {% csrf_token %} {{ form.as_p }}
      <button class="btn" type="submit">Add Product</button>
    </form>
  </body>
</html>
<br /><br /><br /><br /><br /><br /><br />

{% endblock %}

Eco store/templates/App_Shop/checkout1.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container mt-5">
    <h2 class="mb-3">
        Shipping Address <span class="text-muted">Checkout</span>
    </h2>
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-5" style="height: auto;">
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn btn-success btn-lg btn-block mt-3 float-right" type="submit">Save Address</button>
                    </form>
                </div>

            </div>

        </div>
        <div class="col-md-3">
            <div class="card" style="height: auto;">
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for order_item in order_items %}
                            <li class="list-group-item">{{order_item.item.name}} x {{order_item.quantity}}</li>
                        {% endfor %}
                    </ul>

                </div>
                <div class="card-footer">
                    <span class="float-left"><b>Order Total</b></span>
                    <span class="float-right"><b>Ugx. {{order_total}}</b></span>
                </div>
            </div>
            <br>
            {% if saved_address.is_fully_filled %}
                <a href="{% url 'App_Shop:payment' %}" class="btn btn-success btn-lg btn-block mt-3">Payment</a> 
            {% else %}
            <div class="alert alert-info">
                <p>Please fill up all the information before payment.</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

Eco store/templates/App_Shop/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="5; url={% url 'App_Shop:home' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Payment Status</title>
</head>
<body>
    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    
</body>
</html>

Eco store/templates/App_Shop/home.html
{% extends "base.html" %}
{% block body_block %}
<style>

    
</style>
<div class="container my-5">
    <h2 class="my-5">Featured Products</h2>
    <div class="row">
        {% for product in object_list %}
        <div class="col-md-6 col-sm-12 col-lg-3">
            <figure class="card card-product">
                <div class="img-wrap">
                    <img src="/media/{{product.mainimage}}" style="width: 100%; height:300px;">
                </div>
                <figcaption class="info-wrap">
                    <h6 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk %}" style="color:black">{{product.name}}</a></h6>
                    <div class="action-wrap">
                        <div class="price-wrap h5">
                            <span class="price-new">Ugx. {{product.price}}</span>
                            <span class="price-old">Ugx. {{product.old_price}}</span>
                        </div>
                    </div>
                </figcaption>

            </figure>
        </div>     
        {% endfor %}
    </div>
</div>

{% endblock %}

Eco store/templates/App_Shop/order.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container mt-5">
  <h2 class="text-center"><strong>Your Orders</strong></h2>
  <div class="row">
    <div class="col-md-12">
      <div class="card mt-5" style="height:auto">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Order Id</th>
                <th scope="col">Products</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="#">{{ order.orderId }}</a></td>
                <td>
                  {% for item in order.orderitems.all %} {{item}} <br> {% endfor %}
                </td>
                <td><span class="badge badge-primary">Processing Your Order</span></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-12 my-5 text-center">
      <a href="{% url 'App_Shop:home' %}">Bact to Home</a>
    </div>
  </div>
</div>
{% endblock %}

Eco store/templates/App_Shop/payment.html
{% extends 'base.html'%}
{% block body_block %}
Payment
</div><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

Eco store/templates/App_Shop/product_detail.html
{% extends 'base.html'%}
{% block body_block %}
<style>

</style>
<div class="container my-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                            <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px"></a>
                        </div>        
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{object.name}}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">Ugx. </span><span class:"num">{{object.price}}</span>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt>Description</dt>
                        <dd>
                            <p>{{object.detail_text|linebreaks}}</p>
                        </dd>
                    </dl>
                    <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i>Add to Cart</a>
                </article>
            </aside>
        </div>
    </div>
</div><br><br><br><br><br><br><br><br><br><br><br><br><br></div><br><br><br><br><br><br><br><br><br><br><br><br><br></div><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

Eco store/templates/App_Shop/register_business.html
{% extends 'base.html'%}
{% block body_block %}
<style>
    body{
        font-family: sans-serif;
        text-align: center;
        background-color: ghostwhite;
        background-position: center;
        background-size: cover;
    }

    .form{
        display: flex;
        flex-direction: column;
        margin: 6% auto;
        align-items: center;
        width: 700px;
        height: 90%;
        background: rgb(250, 248, 248);
        text-align: center;
        padding: 20px;
        border: 1px solid whitesmoke;
        box-shadow: 15px 20px 20px #504e4eee;
        border-radius: 15px;
        text-align: left;
        
    }
    .register{
        width: 400px;
        padding: 10px 20px;
        display: block;
        border: 0;
        outline: none;
        margin: auto;
        color: whitesmoke;
        background: #04eb49;
        margin-top: 15px;
        border-radius: 15px;
        transition: 0.3s ease;

    }
    .register:hover{
        background-color: brown;
    }
    .box{
        display: flex;
        background-color: rgb(248, 246, 242);
        width: 450px;
        padding: 8px;
        border: none;
        border-bottom: 5px solid rgb(194, 28, 28);
        transition: 0.3s ease;

    }
</style>
<h1 style="color: gray;">Business Form</h1>
<form class="form" method="POST">
    {% csrf_token %}
    <h1 style="text-align: center;">Register Business</h1>
    {{form.as_p}}
    <button class= "register" type="submit">Register Business</button>

</form>

</div><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

Eco store/templates/App_Shop/search.html
{% extends "base.html" %} {% block body_block %}
<style>
    body{
        background-color: silver;
        text-align: center;
    }
    form{
        background: whitesmoke;
        border-radius: 20px;
        background: transparent;
        margin-top: 30px;
        
    }
    .btn{
        width: 150px;
        background-color: blue;
        color: white;
        font-size: 18px;
        border-radius: 15px;
        transition: 0.3s ease;
    }
    .btn:hover{
        background-color: rgb(61, 233, 26);
    }
    .see{
        border: 2px solid;
        border-radius: 15px;
        width: 200px;
        font-size: 18px;
        height: 35px;
        padding-bottom: 8px;
    }
</style>

<h1 style="color: darkslategray;">Search Products</h1>
<form action="" method="POST">
  {%csrf_token%}
  <input type="text" class="see" placeholder="Search" name="search" />
  <button type="submit" class="btn">Search</button>
</form>

{%if searched%} 

{%for product in searched%} 
<div class="container my-5">
    <h2 class="my-5"></h2>
    <div class="row">
        
        <div class="col-md-6 col-sm-12 col-lg-3">
            <figure class="card card-product">
                <div class="img-wrap">
                    <img src="/media/{{product.mainimage}}" style="width: 100%; height:300px;">
                </div>
                <figcaption class="info-wrap">
                    <h6 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk %}" style="color:black">{{product.name}}</a></h6>
                    <div class="action-wrap">
                        <div class="price-wrap h5">
                            <span class="price-new">Ugx. {{product.price}}</span>
                            <span class="price-old">Ugx. {{product.old_price}}</span>
                        </div>
                    </div>
                </figcaption>

            </figure>
        </div>     
        
    </div>
</div>
{%endfor%}

 {%endif%}
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
{% endblock %}