Eco store/App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

Eco store/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

Eco store/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add_product', views.add_product, name='add_product'),
    path('search', views.search, name='search'),
    path('register_business', views.register_business, name='register_business'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('about', views.about, name='aboutpage')
]

Eco store/ecommerce_website_django/urls.py
from django.contrib import admin
from django.urls import path, include

#To show media file
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('accounts/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('about/', include('App_Shop.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco store/templates/about.html
{% extends 'base.html' %}

{% block title_block %}Login{% endblock %}
{% block body_block %}

<style>
  body {
    font-family: sans-serif;
    margin: 0;
    padding: 0;
    background-image: url("88.jpg"); 
    background-repeat: repeat;
  }
  
  header {
    align-items: center;
    font-size: 31px;
    justify-content: space-between;
    top: 0px;
    right: 0px;
    padding: 20px 80px;
    top: 0;
    right: 0;
    background-color: black;
  }
  
  
  header h1 {
    text-align: center;
    font-size: 2em;
    margin: 0;
  }
  
  main {
    padding: 50px 0;
  }
  
  section {
    display: flex;
    position: relative; 
  }
  
  .about-content {
    flex: 2;
    padding: 20px;
    background-color: rgba(156, 123, 123, 0.8);
    border-radius: 4px;
    background: transparent;
  }
  
  h2 {
    margin-bottom: 15px;
  }
  
  p {
    line-height: 1.5;
  }
  
  .team-photo-container {
    flex: 1;
    padding-top: 80px;
    position: relative; 
    
  }
  
  .team-photo {
    width: 100%;
    object-fit: cover;
    border-radius: 4px;
  }
  
  .team-photo-container::after {  
    content: "";
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: url("images/overlay-pattern.png"); 
    background-repeat: repeat;
    opacity: 0.3;
  }
  
  footer {
    font-size: 25px;
    text-align: center;
    padding: 10px;
    background-color: black;
  }
  .about-us{
    display: flex;
    position: relative;
  }
  .we{
    background-color: rgb(174, 235, 235);
    margin: 0;
    
   
  }
  .reachus{
    background-color: grey;
  
  }
  #home{
    padding: 10px;
    border-radius: 10px;
    font-size: 16px;
    margin-bottom: 5px;
    position: relative;
    color: rgb(90, 5, 5);
    background-color: goldenrod;
    cursor: pointer;
  }
  .about-content #home{
    margin-top: -150px;
  }
</style>

  <main>
    <section class="about-us">
      
      <div class="about-content">


        <div class="we">
          <h2><i class="ri-task-line"></i>Our Mission</h2>
          <p>Our mission is to provide quality online business services to our clients or customers</p>
          <h2>Our Team<i class="ri-team-line"></i></h2>
          <p>We are a great team that work together and headed by our Leader Kamuli Bob</p>
        </div>
        <div class="reachus">
          <h2></i><i class="ri-contacts-book-2-line"></i>Contact Us<i class="ri-contacts-line"></i></h2>
          <p>Contact phone: 0742098888</p>
          <p>Email Address: eco@gmail.com</p>
          <h2>Eco-Store Info<i class="ri-information-fill"></i></h2>
          <p>Eco- Store is an online website that enables businessmen to manage their businesses online</p>
          <p>It helps our customers to conduct online businesses</p>
        </div>
      </div>
      <div class="team-photo-container">
        <img src="buggatti.jpg" alt="Team Photo">
      </div>
    </section>
  </main>

{% endblock %}

Eco store/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">  
    <title>{% block title_block %} Eco store {% endblock %}</title>
    <style>
        .card{
            height: 350px;
        }
        .card-product:after{
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }
        .card-product .price-new, .card-product .price{
            margin-right: 5px;
        }
        .card-product .price-old{
            color: #999;
            text-decoration: line-through;
        }
        .card-product .img-wrap{
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }
        .card-product .img-wrap img{
            max-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }
        .card-product .info-wrap{
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .action-wrap{
            padding-top: 4px;
            margin-top: 4px;
        }
        .card-product .bottom-wrap{
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .title{
            margin-top: 0px;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">X</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        {% block body_block %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <footer style="background:black; height:auto; padding:15px;">
        <div class="nav">
           <ul>
              <li><a class="active" href="{%url 'App_Shop:home'%}"><span>Home</span></a></li><br>
              <li><a href="#"><span>Sign in/Register</span></a></li><br>
              <li><a href="/about"><span>About Us</span></a></li><br>
              <li><a href="#"><span>Help and Contact</span></a></li><br>
           </ul>
        </div>
        <hr><br>
        <div style="text-align:center;">
           <a href="#">Privacy</a>,<a href="#">User Agreement</a>,<a href="#">Cookies&Adchoice</a><br>
           <p>&copy 2024 ECOSTORE</p><br>
        </div><br>
     </footer>
</body>
</html>

Eco store/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home'%}"><h2><span style="color:red; width:50px;">ec</span><span style="color:green;">oS</span><span
            style="color:blue;">TO</span><span style="color:gold;">RE</span></h2></a>
            <a class="navbar-brand" href="{% url 'App_Shop:search'%}">Search</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span
                class="navbar-toggler-icon"></span> </button> 
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Order:cart' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i><span class="badge badge-light">{{request.user | cart_total}}</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'App_Login:profile'%}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Orders</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Shop:register_business'%}">Register a Business</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Shop:add_product'%}">Add Products</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Login:logout'%}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:signup' %}" class="btn btn-primary">Signup</a>
                    <a class="nav-link" href="{% url 'App_Login:login'%}" class="btn btn-primary">Login</a>
                </li>
                {% endif %}
            </ul>
    </div>
</nav>