Eco store/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

Eco store/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add_product', views.add_product, name='add_product'),
    path('search', views.search, name='search'),
    path('register_business', views.register_business, name='register_business'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('about', views.about, name='aboutpage')
]

Eco store/ecommerce_website_django/urls.py
from django.contrib import admin
from django.urls import path, include

#To show media file
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('accounts/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('about/', include('App_Shop.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco store/App_Order/models.py
from django.db import models
from django.conf import settings

# Model import
from App_Shop.models import Product

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.quantity} X {self.item}"
    
    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.0f')
        return float_total

class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=100, blank=True, null=True)
    orderId = models.CharField(max_length=100, blank=True, null=True)
    
    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += int(order_item.get_total())
        return total

Eco store/App_Order/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Authentication
from django.contrib.auth.decorators import login_required

# Models
from .models import Cart, Order
from App_Shop.models import Product
# Messages
from django.contrib import messages

# Create your views here.

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        
        # Check if the order item is in the order
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "This item quantity was updated.")
            return redirect("App_Shop:home")
        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Shop:home")
    else:
        order = Order(user=request.user)
        order.save() 
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your cart.")
        return redirect("App_Shop:home")

@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'App_Order/cart.html', context={'carts': carts, 'order': order})
    else:
        messages.warning(request, "You don't have any item in your cart.")
        return redirect("App_Shop:home")

@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.warning(request, "This item was removed from your cart.")
            return redirect("App_Order:cart")
        else:
            messages.info(request, "This item was not in your cart.")
            return redirect("App_Shop:home")
    else:
        messages.info(request, "You don't have any active order.")
        return redirect("App_Shop:home")

@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            # Call an itme from the cart
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            order_item.quantity += 1
            order_item.save()
            messages.info(request, f"{item.name} quantity was updated.")
            return redirect("App_Order:cart")
        else:
            messages.info(request, f"{item.name} is not in your cart.")
            return redirect("App_Shop:home")
    else:
        messages.info(request, "You don't have any active order.")
        return redirect("App_Shop:home")

@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            # Call an itme from the cart
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, f"{item.name} quantity was updated.")
                return redirect("App_Order:cart")
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
            messages.info(request, f"{item.name} quantity was updated.")
            return redirect("App_Order:cart")
        else:
            messages.info(request, f"{item.name} is not in your cart.")
            return redirect("App_Shop:home")
    else:
        messages.info(request, "You don't have any active order.")
        return redirect("App_Shop:home")

Eco store/templates/App_Order/cart.html
{% extends 'base.html'%}
{% block body_block%}
<div class="container my-5">
    <div class="my-5">
        <h2>Your Cart</h2>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" width="15%">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col" align="right">Price</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in carts %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{cart.item.name}}</td>
                <td>
                    <a href="{% url 'App_Order:decrease' pk=cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                    {{cart.quantity}}
                    <a href="{% url 'App_Order:increase' pk=cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                </td>
                <td align="right">Ugx. {{cart.get_total}}</td>
                <td><a href="{% url 'App_Order:remove' pk=cart.item.pk %}"><i class="fas fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td colspan="2">Total</td>
                <td align="right">Ugx. {{order.get_totals}}</td>
                <td></td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right">
                    <a href="{% url 'App_Shop:home' %}" class="btn btn-warning mr-4">Continue Shopping</a>
                    <a href="{% url 'App_Shop:home' %}" class="btn btn-success mr-4">Checkout</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}